---
title: "Citation counts analysis"
author: "Alan Jern"
date: "8/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(here)
```


# Load data
```{r}

citations <- read_csv(here("Citation counts", "Data","wos-citation-data.csv"))
```

# Plot data
```{r plot}

ggplot(data = citations,
       mapping = aes(x = times_cited, color = as.factor(published_year))) +
  geom_freqpoly(binwidth = 100) +
  facet_wrap(vars(subject)) +
  xlim(c(0,4000)) +
  scale_y_log10(breaks = c(10, 1000, 100000),
                labels = c("10", "1000", "100000")) +
  labs(
    title = "Across academic fields, very few papers have much influence",
    subtitle = "26% of philosophy papers published in 2000 have never been cited",
    caption = "Data: Web of Science",
    x = "Number of citations",
    y = "Number of papers",
    color = "Publication year"
  ) +
  theme(
    legend.position = "top"
  )

ggsave("citation_counts.png", width = 6, height = 4, units = "in")
```

